### ISSUE TITLE
No sound on stream when using `play_latest`

### ISSUE THREAD

**Issue by agdamsbo** [TermeHansen/home-assistant-drtv-play#4]
When I use `play_channel`, I can stream to both dlna renderer and chromecast with sound and all.

using `play_latest` the stream starts on the dlna renderer, but without audio. On the chromecast it is stuck at buffering. It shows correct program title and picture. There is no log from the dlna.

Here is the log trying to play on chromecast:
```
Logger: homeassistant.core
Source: components/cast/media_player.py:750
First occurred: 19:55:39 (1 occurrences)
Last logged: 19:55:39

Error executing service: <ServiceCall media_player.play_media (c:01H0G8TH5ER65BX229PG5D6PH3): entity_id=['media_player.stue_cast'], extra=title=Boost dit budget: Farvel til hamsterhjulet, thumb=https://production-static.dr-massive.com/shain/v1/dataservice/ResizeImage/$value?Format='jpg'&Quality=85&EntityType='Item'&EntityId='381844'&Width=1920&Height=1080&ImageId='45961486', media_type=video, media_id=https://drod21d.akamaized.net/all/clear/none/9c/6458f4a179d2c9111cf0949c/00952328040/stream_fmp4/master_manifest.m3u8>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1867, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 750, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pychromecast/quick_play.py", line 78, in quick_play
    controller.quick_play(**data)
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/media.py", line 547, in quick_play
    raise PyChromecastError()  # pylint: disable=broad-exception-raised
pychromecast.error.PyChromecastError
```

and

```
Logger: pychromecast.controllers
Source: /usr/local/lib/python3.10/site-packages/pychromecast/controllers/media.py:544
First occurred: 19:55:39 (1 occurrences)
Last logged: 19:55:39

Quick Play failed for https://drod21d.akamaized.net/all/clear/none/9c/6458f4a179d2c9111cf0949c/00952328040/stream_fmp4/master_manifest.m3u8:video({'title': 'Boost dit budget: Farvel til hamsterhjulet', 'thumb': "https://production-static.dr-massive.com/shain/v1/dataservice/ResizeImage/$value?Format='jpg'&Quality=85&EntityType='Item'&EntityId='381844'&Width=1920&Height=1080&ImageId='45961486'"})
```

**Comment by agdamsbo** [comment]
I think the issue might be the same as here  [Feature Request: Play Live TV from Plex via cast or androidTV #39](https://github.com/JurajNyiri/PlexMeetsHomeAssistant/issues/39) and here [ Add #66: VLC media player Telnet #67](https://github.com/JurajNyiri/PlexMeetsHomeAssistant/pull/67). As I gather, the issue is about .m3u8 streams.

**Comment by TermeHansen** [comment]
Can you try to change:

`                'media_content_type': 'video',
`
to
`                'media_content_type': 'video/mp4',
`

for the play_latest function, and see if it helps for you. My Sony tv gives me:

```
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/braviatv/coordinator.py", line 314, in async_play_media
homeassistant  |     raise ValueError(f"Invalid media type: {media_type}")
homeassistant  | ValueError: Invalid media type: video/mp4

```
but I think that might be a HA bug...

**Comment by TermeHansen** [comment]
https://www.home-assistant.io/integrations/cast/

we could also see if bubbleupnp works, but the best would be if the correct MIME type would solve it...

**Comment by agdamsbo** [comment]
I will try to go through some more testing including bubbleupnp.

I see that streaming m3u8 files has been discussed a bit. This thread seems a little discouraging:  [The m3u8 can't play via chrome cast on Home Assistant 2021.12.1 #61787](https://github.com/home-assistant/core/issues/61787), but there might be some suggestions [here on reddit](https://www.reddit.com/r/homeassistant/comments/a99k4y/play_m3u8_hls_stream_on_chromecast/).

**Comment by agdamsbo** [comment]
From what I gather, chromecasts seems to be very picky about the streaming format.
Do you have streaming with audio working on your system with `play_latest` @TermeHansen ? Maybe the dlna renderer should be the focus instead of the picky chromecast?
I have a smooth picture on dlna, but lacking sound for now.

**Comment by TermeHansen** [comment]
No Dlna renderer for my Sony tv does not start at all... I use Kodi mainly and also here with HA it just eats everything I throw at it 🤗

But yes if I can get my Sony tv to work with Dlna renderer it will s probably a good baseline...

**Comment by agdamsbo** [comment]
Long live Kodi!

**Comment by agdamsbo** [comment]
OK. So life happened... Can't get anything but play_channel to work. Having traditional flow TV working is also something ✌️ got around to setting up my kodi box again.
